#!/usr/bin/env python3
"""
heading-labels.py — the subgoal labels that replaced the four generic headings.

Tier 0 of the Teaching Standard retired four filler section titles that had worn
out across the corpus: "The Mental Model" (65x), "Practical Usage" (64x),
"Internals & Edge Cases" (64x) and "Failure Modes and Interpretation" (80x).
A heading a reader has seen sixty-five times is invisible, and none of the four
said anything about the section beneath it.

Each was replaced with a label naming the move that section actually makes,
written from that section's own content. Kept here as the record of what changed
and as the input to relabel-headings.py.

Keys are (note stem, kind) where kind is M / P / I / F for the four old titles.
"""
# (note stem, kind) -> new heading.  M=The Mental Model  P=Practical Usage
# I=Internals & Edge Cases  F=Failure Modes and Interpretation
LABELS = {
# ── Offensive Security ────────────────────────────────────────────────────────
("Code-Reuse Attacks (ROP, JOP & SROP)","F"): "When the gadget you need isn't in the binary",
("Exploit Reliability & Mitigation Engineering","F"): "Why a working PoC dies on the next host",
("Shellcode Engineering","F"): "The bytes that silently truncate your payload",
("Binary Exploitation Fundamentals","F"): "Off by a few bytes, and what that costs",
("CPU, Assembly & the ABI","F"): "Calling conventions that fail silently",
("Executable Formats: ELF, PE & Mach-O","F"): "GOT assumptions that modern binaries break",
("Fuzzing, Debugging & Crash Triage","F"): "Why a crash is not yet a weapon",
("Heap Exploitation & Use-After-Free","F"): "When the heap layout refuses to repeat",
("Integer, Type Confusion & Format String Bugs","F"): "Why the crash site is rarely the bug",
("Stack Corruption","F"): "Overflows that never touch the return address",
("Browser Exploitation Theory","F"): "Why renderer RCE is not game over",
("Kernel Exploitation Theory","F"): "Working on a target that panics when you're wrong",
("Userland Exploitation: Linux & Windows","F"): "The ABI mistakes that break cross-platform payloads",
("API Security Fundamentals","F"): "Testing one authorization dimension and missing half the risk",
("Legacy XML Web Services Testing","F"): "Proving XXE without causing the disclosure",
("Modern API Security Testing","F"): "Confirming BOLA without crossing into mass data access",
("WebSocket Security Testing","F"): "The WAF blind spot both sides miss",
("Active Directory Architecture & Enumeration","F"): "Enumeration that announces itself",
("Active Directory Certificate Services Security","F"): "Why you forge against a canary, never a real admin",
("Active Directory Privilege Escalation","F"): "Techniques that change the directory you're testing",
("Domain Persistence & Trust Abuse","F"): "The most destructive actions in this domain",
("Kerberos & NTLM Attacks","F"): "Cracking only what you are allowed to crack",
("NTLM Relay & Authentication Coercion","F"): "Coercion aimed at the wrong machine",
("Guided Network Pentest Walkthrough","F"): "Testing an asset that turns out not to be theirs",
("Guided Red Team & Purple Team Operation","F"): "Why being inside doesn't retire the rules",
("Guided Web & API Assessment","F"): "The setup failure that makes authorization untestable",
("Penetration Testing Standards & Frameworks","F"): "Why a framework is a loop, not a checklist",
("Rules of Engagement & Scoping","F"): "The one error that is also a crime",
("Threat Modeling & MITRE ATT&CK","F"): "Modeling an adversary the client will never face",
("External Network Pentesting","F"): "Attribution errors and what they cost",
("Internal Network Pentesting","F"): "Blast radius inside a production network",
("Layer 2 & 3 Network Attacks","F"): "How a scoped test black-holes a whole VLAN",
("Remote Access Security Testing","F"): "When password spraying becomes denial of service",
("Service Enumeration","F"): "Where enumeration drifts into account lockout",
("Credential Access & Secret Hunting","F"): "Collecting enough to prove it, and no more",
("Data Collection & Post-Exploitation Cleanup","F"): "The breach you cause yourself",
("Local Privilege Escalation","F"): "Why kernel exploits come last",
("Persistence Techniques","F"): "Every mechanism you plant, you must remove",
("Pivoting & Tunneling","F"): "The tunnel you forget is a backdoor you built",
("Active Reconnaissance & Port Scanning","F"): "Filtered is not closed, and other misreads",
("Cloud & Internet Exposure Discovery","F"): "Why a cloud IP may not be your target's tomorrow",
("DNS & Subdomain Reconnaissance","F"): "How wildcard DNS makes brute-force meaningless",
("Passive Reconnaissance & OSINT","F"): "Findings that describe a decommissioned asset",
("Evidence & Risk Prioritization","F"): "Over-collection as a liability you created",
("Finding & Report Writing","F"): "The difference between a report and a scanner export",
("Purple Team Exercise Design","F"): "Design errors that make a failure impossible to localise",
("Retesting, Closure & Lessons Learned","F"): "The superficial fix that passes a naive retest",
("Continuous Exposure & Remediation Validation","F"): "Closed findings that were never verified",
("Manual Vulnerability Verification","F"): "Where verification turns into exploitation",
("Vulnerability Intelligence & Scoring","F"): "Drowning in criticals while the exploited flaw waits",
("Vulnerability Scanning & Automation","F"): "Every scanner finding is a hypothesis",
("Business Logic Testing","F"): "Proving a money bug without moving money",
("Race Condition & Concurrency Testing","F"): "Why sequential requests wrongly prove 'safe'",
("Framework & CMS Testing Methodology","F"): "When the absence of a fingerprint proves nothing",
("WordPress Security Testing","F"): "Prioritising by exploitability, not by plugin count",
("CORS & Clickjacking","F"): "The CORS finding that isn't exploitable",
("CSRF & SameSite Testing","F"): "Proving state change without a real transfer",
("Cross-Site Scripting","F"): "Where proof of execution becomes the attack",
("Prototype Pollution & DOM Security","F"): "Pollution with no gadget is still a finding",
("File Inclusion & Path Traversal","F"): "Choosing the most benign file that proves the crossing",
("File Upload Security Testing","F"): "A marker file, not a working web shell",
("Insecure Deserialization Testing","F"): "Benign side effects as proof of code execution",
("XML External Entity Testing","F"): "Aiming an XXE probe somewhere safe",
("HTTP Request Smuggling","F"): "Why this one belongs in a lab",
("Server-Side Request Forgery","F"): "Canary services instead of real metadata endpoints",
("WAF Testing & Bypass Methodology","F"): "Why 'protected by WAF' is not a finding",
("Web Cache Attacks","F"): "Attacks that hit everyone but the tester",
("Broken Access Control","F"): "One cross-user access proves it; enumeration is a breach",
("Federated Identity & SSO","F"): "Forging assertions without impersonating real people",
("JWT Security Testing","F"): "When alg:none is already patched",
("MFA, Recovery & Session Bypass Testing","F"): "MFA present is not MFA enforced",
("Web Authentication Testing","F"): "Brute force as an outage you caused",
("SQL Injection","M"): "The boundary between grammar and data",
("C2 Infrastructure & Redirectors","F"): "Pointing agents straight at your control server",
("Operational Security, Anti-Forensics & Teardown","F"): "The artifact you forgot is exposure you created",
("AV, EDR & Telemetry Evasion Testing","F"): "Beating static AV and calling it evasion",
("Payload Engineering & Obfuscation","F"): "Why obfuscation does nothing to behavioural detection",
("Process Injection & Direct Syscalls","F"): "Injection blends the action, not the act",
("Data Collection & Exfiltration Simulation","F"): "Canary datasets and channel signatures",
("Red Team Credential Access & Lateral Movement","F"): "Why the red team takes the quiet path, not every path",
("Red Team Campaign Planning & Initial Access","F"): "Optimising for measurement, not for stealth",
}

TOOLING = {
"Bash": ("Where Bash belongs: gluing tools, not building logic",
         "The safety preamble, and quoting everything",
         "Word splitting: the failure that is also a vulnerability"),
"C++": ("Maximum control, and no memory-safety net",
        "RAII, smart pointers, and bounding every access",
        "Why the worst bugs stay silent until someone exploits them"),
"Go": ("One static binary, cheap concurrency",
       "A worker pool over channels",
       "When goroutines are so cheap you launch too many"),
"Python": ("The rapid-development corner of the map",
           "A bounded async probe in a reproducible environment",
           "The GIL, and the concurrency model it forces on you"),
"Sysmon": ("The event stream: CCTV for the operating system",
           "Installing it with a config that records something",
           "The config is both the power and the blind spot"),
"osquery": ("The flashlight: what is true right now",
            "Interactive queries first, scheduled ones after",
            "A snapshot cannot see what already exited"),
"CyberChef": ("The decode lens: what is hidden inside this?",
              "Building a recipe that updates as you drag",
              "Why deobfuscation order decides whether you get anything"),
"Volatility": ("The memory lens: runtime truth a disk cannot show",
               "Running plugins against a dump",
               "The one threat class disk analysis cannot touch"),
"YARA": ("The classify lens: strings plus a condition",
         "Writing a rule, then scanning with it",
         "Packing, and why on-disk strings vanish"),
"Snort": ("Matching traffic against known-bad patterns",
          "Reading a rule: action, protocol, direction, options",
          "How literal matching gets encoded around"),
"Suricata": ("One engine doing both signatures and protocol logging",
             "Snort grammar in, eve.json out",
             "Where IDS mode becomes an outage"),
"Zeek": ("Recording behaviour instead of matching signatures",
         "Pointing it at an interface and reading the logs",
         "Why 'no alerts' means it is working"),
"Wireshark": ("Peeling nested layers and naming every field",
              "Display filters and Follow Stream",
              "Capture filter versus display filter"),
"tcpdump": ("Deciding in the kernel which packets are worth keeping",
            "The canonical capture, written to a file",
            "How omitting -n pollutes your own capture"),
"Sigma": ("The portable half of the detection pipeline",
          "Logsource, detection, condition, then compile",
          "The field taxonomy that makes a valid rule never fire"),
"Splunk Basics": ("Where the logs go to be searched at scale",
                  "Start narrow, then transform",
                  "Bounding a search before it scans everything"),
"BloodHound": ("Active Directory as a directed graph",
               "Collect, import, mark owned, query",
               "Possible paths versus reachable ones"),
"Impacket": ("The execution engine of the AD attack chain",
             "One credential syntax across every script",
             "Pass-the-hash, and what it reveals about NTLM"),
"NetExec": ("One credential, checked everywhere at once",
            "Pointing it at a range, and reading (Pwned!)",
            "Spraying has a direction, and backwards locks the domain"),
"Responder": ("Getting a hash with no credentials at all",
              "Listening, then cracking offline",
              "Why a Responder capture cannot be passed"),
"Gobuster": ("Inferring what exists from status codes",
             "Modes: paths, vhosts, subdomains",
             "Calibrating against a server that lies about 404"),
"Netcat": ("Connecting two byte streams",
           "Banner grabs, listeners, and file transfer",
           "The framing that higher-level clients hide"),
"dirsearch": ("Asking for thousands of paths and watching the codes",
              "The -e extension expansion",
              "When a fixed-size 200 masquerades as a hit"),
"enum4linux": ("SMB defaults built to be helpful",
               "What a null session hands you",
               "One registry value, two completely different answers"),
"feroxbuster": ("Recursion as the one added idea",
                "Watching it dig into what it finds",
                "How a soft-404 makes recursion explode"),
"ffuf": ("Put FUZZ here, and define what counts as interesting",
         "Moving the keyword to fuzz any position",
         "Clusterbomb, and the combinatorics that bite you"),
"Hydra": ("Guessing credentials against a live service",
          "The syntax, kept deliberately gentle",
          "Where the failure string lies to you"),
"Metasploit Framework": ("Three nouns: exploit, payload, listener",
                         "The console loop: search, use, set, exploit",
                         "Staged versus stageless, and where footholds die"),
"Masscan": ("The first move of a SYN scan, and nothing else",
            "Scope in a config file, reviewed before it runs",
            "Statelessness, and what it encodes into the packet"),
"Nmap": ("Inferring state from a reply, or from silence",
         "The flags you actually use, grouped by phase",
         "Why -sS and -sT are a detection choice"),
"RustScan": ("Letting the OS complete the handshake",
             "Everything after -- goes straight to Nmap",
             "Batch size against the file-descriptor ceiling"),
"Amass": ("Mapping one target's DNS estate into a graph",
          "Passive first, then active inside scope",
          "The flag that turns quiet recon into logged traffic"),
"Shodan": ("Passive recon where the scanning already happened",
           "Filters that make the index surgical",
           "Two opposite failures of a stale snapshot"),
"theHarvester": ("One command fanned out across public sources",
                 "Choosing a source set, and saving the evidence",
                 "Acting on aggregated data without confirming it"),
"Hashcat": ("The same guess-and-compare loop, at GPU scale",
            "Benchmark, then dictionary and mask attacks",
            "The benchmark table read as a hardening spec"),
"John the Ripper": ("Generating smart candidates, not just more of them",
                    "unshadow, then crack with rules",
                    "Why complexity requirements do not help defenders"),
"hash-identifier": ("Reading the structural fingerprint of a hash",
                    "Ranking candidate types, and the -m bridge",
                    "A fixed rule table with no sense of likelihood"),
"name-that-hash": ("Different algorithms leave different shapes",
                   "Identifying one hash, with the crack modes attached",
                   "Reasoning about format instead of matching a database"),
"LinPEAS": ("Finding the one thing that trusts you too much",
            "Running it, and keeping the output as evidence",
            "Reading the colour ranking correctly"),
"WinPEAS": ("The vector families that lead to SYSTEM",
            "The .exe and the .bat fallback",
            "Why the colour ranking is triage, not a verdict"),
"Nessus": ("The widest net at the top of the funnel",
           "Credentials as the biggest lever on result quality",
           "Back-ported fixes and the version-string lie"),
"Nuclei": ("Narrowing the pile to what is actually exploitable",
           "Fresh templates, scoped selection",
           "What separates a good matcher from a bad one"),
"OpenVAS": ("Only as good as its feed",
            "Verifying the components before trusting a scan",
            "How a stale feed reports a clean host"),
"SearchSploit": ("The pivot: is there an exploit for this?",
                 "Search by product and version, then read the code",
                 "A matching title is not an applicable exploit"),
"Burp Suite": ("The most powerful position: the middle",
               "Proxy, scope, and the core loop",
               "Intruder's four attack types, and picking wrong"),
"Nikto": ("Firing a list of known-bad requests at the server",
          "Reading each + as a lead",
          "Why every finding needs manual confirmation"),
"OWASP ZAP": ("Passive reading versus active probing",
              "The CLI, and the CI-friendly baseline scan",
              "What the passive baseline structurally cannot find"),
"Postman": ("Structured input, structured output, gated by auth",
            "Importing a spec, or pasting a curl command",
            "Newman, and turning a collection into a CI gate"),
"SQLmap": ("One request, one parameter, probed deeply",
           "Feeding it a saved request, and the two safety dials",
           "Why time-based inference is a statistical minefield"),
"WPScan": ("A specialist that knows how WordPress leaks",
           "Enumerating plugins and users, and what the token unlocks",
           "Confirming an inferred version before claiming a CVE"),
"curl": ("Four parts of a request, four parts of a response",
         "The everyday verbs, starting with -I",
         "What -k costs you, and why that is the lesson"),
"Aperisolve": ("Data tucked into every layer of an image",
               "Chaining what each tool leaks into the next",
               "Why the format decides which technique is possible"),
"CrackStation": ("Precomputing once, looking up forever",
                 "Identify, confirm unsalted, look it up",
                 "The single fact that is both its power and its limit"),
"GTFOBins": ("Programs that do more than their name suggests",
             "Indexed by the capability you already have",
             "The -p flag, and why shells drop privilege without it"),
"LOLBAS": ("Abusing the trusted binaries already on the box",
           "Indexed by capability, from download to credential dump",
           "Signed and expected, which is the whole problem"),
"revshells.com": ("Exploiting the asymmetry firewalls create",
                  "Listener first, then the payload",
                  "Why a raw shell breaks the moment you need a terminal"),
"Kismet": ("The passive discovery layer you run first",
           "Monitor mode, and the live web UI",
           "Probe requests, and what phones announce about people"),
"aircrack-ng": ("You cannot break WPA2, so you capture the handshake",
                "The pipeline from monitor mode to offline crack",
                "Why identical captures crack in seconds, or never"),
"hcxtools": ("Clientless capture, and the limitation it removes",
             "Capture, convert, crack",
             "When there is no PMKID to take"),
"Building Network Scanners": ("One tiny question, answered concurrently",
                              "A bounded async probe behind a semaphore",
                              "Two concurrency mistakes that break a working scanner"),
"Command & Control Design Principles": ("A topology built so the operator is never exposed",
                                        "Beacon behaviour as the dominant tunable",
                                        "The metronome that gives a beginner C2 away"),
"Hashsmith Tool Architecture": ("The well-built-tool diagram applied to hashing",
                                "Explicit subcommands, machine-readable output",
                                "Designing a tool that refuses to over-claim"),
"Security Tool Architecture & Design Patterns": ("Separating the engine from the edges",
                                                 "Logic that knows nothing about CLI or output",
                                                 "The god script, and the moment you try to test it"),
"ShadowStep Tool Architecture": ("A scope gate every action must pass",
                                 "Plan, act inside scope, then verify",
                                 "Proving that anti-forensics is detectable"),
}
for stem,(m,p,i) in TOOLING.items():
    LABELS[(stem,"M")] = m
    LABELS[(stem,"P")] = p
    LABELS[(stem,"I")] = i
